version: '3.8'

volumes:
  postgres:


services:

  postgres:
    image: postgres:16.1
    restart: always
    environment:
      - POSTGRES_USER=${PGSQL_USER}
      - POSTGRES_PASSWORD=${PGSQL_USER}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - ${PGSQL_PORT}:5432
      
  phppgadmin:
    build: ./docker/phppgadmin/.
    restart: always
    depends_on: 
      - postgres
    ports:
      - ${PHPPGADMIN_PORT}:80
    environment: 
      PHP_PG_ADMIN_SERVER_PG_DUMP_PATH: /usr/bin/pg_dump
      PHP_PG_ADMIN_SERVER_PG_DUMPALL_PATH: /usr/bin/pg_dumpall
      PHP_PG_ADMIN_SERVER_HOST: postgres